services:
  db:
    image: postgres
    restart: always
    container_name: 'ohmyblog-postgres'
    environment:
      POSTGRES_DB: 'ohmyblog'
      POSTGRES_USER: 'ohmyblog'
      POSTGRES_PASSWORD: 'Ohmyblog123'
      POSTGRES_RANDOM_ROOT_PASSWORD: 'yes' 
      TZ: 'UTC-6'
    ports:
      - 5432:5432
  app:
    image: ohmyblog-dotnet
    container_name: "server"
    depends_on:
      - db
    ports:
      - 8080:8080